server:
  port: 80
  tomcat:
    max-threads: 128
    uri-encoding: utf-8

spring:
  application:
    name: jdej-manage-dev
#  datasource:
#    primary:
#      url: jdbc:mysql://127.0.0.1:3306/ej?characterEncoding=utf-8&useSSL=false
#      username: root
#      password: root
#      driver-class-name: com.mysql.jdbc.Driver
#      initial-size: 1
#      min-idle: 3
#      max-idle: 10
#      max-active: 10
#      max-wait: 60000
#      time-between-eviction-runs-millis: 60000
#      min-evictable-idle-time-millis: 300000
#      test-while-idle: true
#      test-on-borrow: false
#      test-on-return: false
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/ej?characterEncoding=utf-8&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    initial-size: 1
    min-idle: 3
    max-idle: 10
    max-active: 10
    max-wait: 60000
    time-between-eviction-runs-millis: 60000
    min-evictable-idle-time-millis: 300000
    test-while-idle: true
    test-on-borrow: false
    test-on-return: false
logging:
  file: ./logs/${spring.application.name}.log
